name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'enhancement'
    branch:
      - '/feat(?:ure)?-.*/'
  - label: 'documentation'
    files:
      - 'docs/**'
      - '*.md'
    branch:
      - '/docs?-.*/'
  - label: 'bugfix'
    branch:
      - '/bug-.*/'
      - '/fix-.*/'
  - label: 'chore'
    files:
      - '.github/*'
    branch:
      - '/chore-.*/'
