/* automatically generated by rust-bindgen 0.69.4 */

pub const EDITORCONFIG_PARSE_NOT_FULL_PATH: i32 = -2;
pub const EDITORCONFIG_PARSE_MEMORY_ERROR: i32 = -3;
pub const EDITORCONFIG_PARSE_VERSION_TOO_NEW: i32 = -4;
pub type editorconfig_handle = *mut ::std::os::raw::c_void;
extern "C" {
    pub fn editorconfig_handle_init() -> editorconfig_handle;
}
extern "C" {
    pub fn editorconfig_handle_destroy(h: editorconfig_handle) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn editorconfig_handle_get_err_file(
        h: editorconfig_handle,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn editorconfig_handle_get_version(
        h: editorconfig_handle,
        major: *mut ::std::os::raw::c_int,
        minor: *mut ::std::os::raw::c_int,
        patch: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn editorconfig_handle_set_version(
        h: editorconfig_handle,
        major: ::std::os::raw::c_int,
        minor: ::std::os::raw::c_int,
        patch: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn editorconfig_handle_set_conf_file_name(
        h: editorconfig_handle,
        conf_file_name: *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn editorconfig_handle_get_conf_file_name(
        h: editorconfig_handle,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn editorconfig_handle_get_name_value(
        h: editorconfig_handle,
        n: ::std::os::raw::c_int,
        name: *mut *const ::std::os::raw::c_char,
        value: *mut *const ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn editorconfig_handle_get_name_value_count(
        h: editorconfig_handle,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn editorconfig_parse(
        full_filename: *const ::std::os::raw::c_char,
        h: editorconfig_handle,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn editorconfig_get_error_msg(
        err_num: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn editorconfig_get_version(
        major: *mut ::std::os::raw::c_int,
        minor: *mut ::std::os::raw::c_int,
        patch: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn editorconfig_get_version_suffix() -> *const ::std::os::raw::c_char;
}
