name: CI on main
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
          bins: taplo-cli
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run format
        run: |
          cargo fmt --all -- --check
          taplo format --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
        with:
          components: clippy
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo check
        run: cargo check --workspace --all-targets --release
      - name: Run clippy
        run: cargo clippy

  check-dependencies:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        run: rustup toolchain install nightly
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install udeps
        run: cargo install cargo-udeps --locked
      - name: Run udeps
        run: cargo +nightly udeps --all-targets

# TODO: run tests
