name: Update Semver
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-semver:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: haya14busa/action-update-semver@v1
        with:
          major_version_tag_only: true
